<?php
//Template Name: Single News Article Template

?>

<?php get_header(); ?>
<div class="single-publication-wrap news">

  <section class="publication-intro">
    <div class="l-container">
      <div class="text col-match">
        <div class="text-container">
          <div class="publication-details">
            Category: Medical Release<br>
            Dated: May 23, 2017<br>
          </div>
          <div class="highlight-headline">
            <h2>Prescription drug use can increase the morbidity and mortality of people who use drugs</h2>
          </div>
          <div class="publication-links">
            <a class="twitter" href="/">
              <svg id="Layer_1" data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 23 18.69"><defs></defs><title>twitter-nobg</title><g id="layer1"><path id="path3611" d="M7.23,18.69A13.34,13.34,0,0,0,20.66,5.27c0-.21,0-.41,0-.61A9.61,9.61,0,0,0,23,2.21,9.56,9.56,0,0,1,20.29,3,4.82,4.82,0,0,0,22.37.35a9.56,9.56,0,0,1-3,1.14,4.72,4.72,0,0,0-8,4.3A13.37,13.37,0,0,1,1.6.86,4.78,4.78,0,0,0,1,3.24a4.7,4.7,0,0,0,2.1,3.92A4.6,4.6,0,0,1,.92,6.57v.06a4.72,4.72,0,0,0,3.79,4.63,4.64,4.64,0,0,1-1.24.17,4.33,4.33,0,0,1-.89-.09A4.72,4.72,0,0,0,7,14.62a9.51,9.51,0,0,1-5.86,2A8.47,8.47,0,0,1,0,16.57a13.35,13.35,0,0,0,7.23,2.12"/></g></svg>
              <span>Share on Twitter</span>
            </a>
            <a class="facebook" href="/">
              <svg id="Layer_1" data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 13.46 25.91"><defs></defs><title>fb-nobg</title><path id="f" d="M8.73,25.91V14.09h4l.59-4.6H8.73V6.54C8.73,5.21,9.1,4.3,11,4.3h2.44V.18A34.72,34.72,0,0,0,9.9,0C6.38,0,4,2.15,4,6.09v3.4H0v4.6H4V25.91Z"/></svg>              
              <span>Share on Facebook</span>
            </a>
            <a class="pdf" href="/">
              <svg id="Layer_1" data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 18.87 22.88"><defs></defs><title>doc-icon</title><path d="M17.69.38H7.35A.68.68,0,0,0,7,.46l0,0a1.09,1.09,0,0,0-.17.13L.61,6.75a1.09,1.09,0,0,0-.13.17l0,0a.73.73,0,0,0-.07.19.86.86,0,0,0,0,.16V21.71a.79.79,0,0,0,.79.8H17.69a.8.8,0,0,0,.8-.8V1.17A.79.79,0,0,0,17.69.38ZM3.11,6.52,6.56,3.09V6.52ZM16.9,2V20.91H2V8.12H7.35a.8.8,0,0,0,.8-.8V2Z"/></svg>
              <span>Download Publication (pdf)</span>
            </a>
          </div>
        </div>
      </div>
    </div>
  </section>

  <section class="article-builder">
    <div class="l-container">
      <div class="content-block text">
        <p class="intro">
          Recommendations from a meeting of over 200 policymakers, public health officials, law enforcement professionals, researchers, people who use drugs, and community organizers provides an innovative roadmap to improve Canada's policy response to illegal drugs over the coming ten years. 
        </p>
        <p>
          Toronto, Canada – Against the backdrop of a national opioid overdose crisis and the fracturing of the global consensus on criminalization-based drug policies, over 200 participants met in Ottawa at Canada's Drug Futures Forum in April 2017 to produce a ten year agenda for the future of Canadian drug policy. A <a href="/">new report</a> outlines wide-ranging recommendations from the Forum, and calls for the exploration and implementation of innovative policies to reduce the harms of drugs and drug policy in Canada.
        </p>
        <p>
          "The regulation of Canada's recreational cannabis market, and a commitment to a growing public health response to the opioid overdose crisis, signal that Canada is now a leader in drug policy innovation," said Dr. Dan Werb, Director of the International Centre for Science in Drug Policy and Chair of the Organizing Committee for the Forum. "The recommendations yielded from Canada's Drug Futures Forum build on this work to offer a roadmap for how to continue this drug policy innovation into the next decade."
        </p>
        <p>
          Available in both English and French, <a href="/">Canada's Drug Futures Forum: Summary of Proceedings and Final Recommendations"</a> synthesizes dialogue generated by speakers at the Forum and outlines recommendations from participants on the future of Canadian drug policy. The recommendations reflect predominant themes and areas of convergence in the Forum's presentations and discussions, although not total consensus, and present opportunities to generate policy or amend existing policies in the short, medium, and long term across five domains, including:
        </p>
        <ul>
          <li>
            National drug policy reform;
          </li>
          <li>
            Criminal justice reform;
          </li>
          <li>
            Prevention, harm reduction, and treatment;
          </li>
          <li>
            Research and knowledge exchange; and,
          </li>
          <li>
            International leadership.
          </li>
        </ul>
        <p>
          "Police professionals and agencies in Canada recognize that more needs to be done to assist people who use drugs in their struggles and challenges," noted Senator Vernon White, who is also a former Chief of Police and Assistant RCMP Commissioner. "The Forum recommendations emphasize the importance of increased levels of medication-assisted therapy, which should be made available for both opioids and other substances. This would help to reduce the criminal elements involved in the drug trade, reduce crimes committed by people who use drugs, and help build recognition of drug dependence as a medical issue to be addressed by medical practitioners."
        </p>
        <p>
          "Canada's recent moves on cannabis regulation, on supervised drug consumption, and on heroin prescription have provided it with a unique opportunity to establish itself as the global model in progressive and evidence-based drug policy," explained Ann Fordham, Executive Director of the U.K.-based International Drug Policy Consortium. "The recommendation emerging from the Forum to establish a federal commission to explore regulation across a broader range of substances is a sensible next step given Canada's pioneering work on cannabis policy reform."
        </p>
        <p>
          A webinar launching the Forum's Summary of Proceedings and Final Recommendations included a presentation of the report highlights, comments from respondents, and an opportunity for attendees to ask questions and discuss next steps. Those interested can <a href="/">watch a recording of the webinar</a> and <a href="/">view the slides</a>.
        </p>
        <p>
          <i>About Canada's Drug Futures Forum</i>
        </p>
        <p>
          From April 4-5, 2017, a multidisciplinary team of scholars convened over 200 researchers, policymakers, public health officials, law enforcement professionals, people who use drugs, and community organizers at <a href="/">Canada's Drug Futures Forum</a> in Ottawa, on traditional Algonquin territory, to examine the future of Canada's domestic and
        </p>
      </div>

      <div class="content-block text">
        <h3>Contact Info</h3>
        <p>
          Nazlee Maghsoudi<br>
          Knowledge Translation Manager<br>
          Centre for Drug Policy Evaluation<br>
          +1 (858) 205-8262<br>
          <a href="mailto:candrugforum@gmail.com">candrugforum@gmail.com</a>
        </p>
      </div>

    </div>
  </section>  
</div>
<?php get_footer(); ?>